In [17]:
import numpy as np

# Create a 1D array

arr1 = np.array([1,2,3])

print(arr1)

[1 2 3]


In [18]:
# check the array

print(type(arr1))

<class 'numpy.ndarray'>


In [19]:
# Check the shape of the array

print(arr1.shape)

(3,)


In [20]:
# accessing elements from the array

arr1[2]

3

In [21]:
# Change an element from the array

arr1[2]= 5

In [22]:
arr1

array([1, 2, 5])

In [24]:
# Create a 2D array

arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [25]:
# Check the shape of the array

print("The shape is 2 rows and 3 columns:", arr2.shape)

The shape is 2 rows and 3 columns: (2, 3)


In [26]:
# Accessing elements from the array

arr2[0][2]

3

In [27]:
arr2[0,2]

3

In [28]:
arr2[0,-2]

2

In [30]:
arr2[0,-1]

3

In [32]:
arr2[-1, 0]

4

In [45]:
# Array of type string

arr3 = np.array(['India', 'China', 'USA' , 'Mexico'])
print(arr3)

['India' 'China' 'USA' 'Mexico']


In [46]:
arr3[1]

'China'

In [49]:
# Array of evenly spaced values within a specified interval

arr = np.arange(0, 20, 2)
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]


In [51]:
# Array of evenly spaced number in a specified interval

arr = np.linspace(0, 10, 20)
print(arr)

[  0.           0.52631579   1.05263158   1.57894737   2.10526316
   2.63157895   3.15789474   3.68421053   4.21052632   4.73684211
   5.26315789   5.78947368   6.31578947   6.84210526   7.36842105
   7.89473684   8.42105263   8.94736842   9.47368421  10.        ]


In [55]:
# Array of random values between 0 and 1 in a given shape

arr = np.random.rand(10)
print(arr)
print('\n')
arr = np.random.rand(3,4)
print(arr)

[ 0.49040995  0.47226165  0.10556096  0.53506425  0.17164791  0.82141653
  0.33300599  0.75698163  0.76909037  0.96925184]


[[ 0.72197329  0.3584691   0.34545225  0.39329763]
 [ 0.68886322  0.49115644  0.55194581  0.90256603]
 [ 0.94748455  0.3168291   0.4499492   0.25973967]]


In [60]:
# Array of zeros

print(np.zeros(10))
print('\n')
print(np.zeros((2,3)))

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


[[ 0.  0.  0.]
 [ 0.  0.  0.]]


In [63]:
print(np.ones((3,4)))

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [70]:
# Array of constant values in a given shape

print(np.full((4,6),10))

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]


In [71]:
# Create an array by repetition
# epeat each element of an array by a specified number of times

arr = [0, 1, 2]
print(np.repeat(arr, 3)) 

[0 0 0 1 1 1 2 2 2]


In [72]:
# Repeat an array by a specified number of times

arr = [0, 1, 2]
print(np.tile(arr, 3))

[0 1 2 0 1 2 0 1 2]


In [73]:
# Create an idenity matrix

identity_matrix = np.eye(3)
print(identity_matrix)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [74]:
identity_matrix = np.identity(3)
print(identity_matrix)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [75]:
# Create a matrix with a specified diagonal array

arr = np.diag([1,2,3,4,5])
print(arr)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [76]:
arr = np.random.rand(5,5)
print(arr)

[[ 0.92442117  0.76175054  0.20185687  0.2738665   0.45570721]
 [ 0.89719214  0.13305234  0.02005525  0.42783675  0.91508155]
 [ 0.73914224  0.42200879  0.00212008  0.14618597  0.35100732]
 [ 0.49504246  0.39017443  0.70696161  0.2292809   0.76391887]
 [ 0.43283068  0.61598609  0.38632981  0.48332     0.57072346]]


In [77]:
# Extract the diagonal elements in the array
print(np.diag(arr))

[ 0.92442117  0.13305234  0.00212008  0.2292809   0.57072346]


In [78]:
# Display the length of the array
print(len(arr))

5


In [80]:
# Display the dimension of the array
print(arr.ndim)

2


In [82]:
# Display the size of the elements
print(arr.size)

25


In [91]:
# print 4 random integers

print(np.random.randint(-10, 10, 4))

[ 6  6 -3  1]


In [93]:
# Mathematical operations

print(arr + 10)
print('\n')
print(arr - 10)
print('\n')
print(arr * 10)
print('\n')
print(arr / 10)

[[ 10.92442117  10.76175054  10.20185687  10.2738665   10.45570721]
 [ 10.89719214  10.13305234  10.02005525  10.42783675  10.91508155]
 [ 10.73914224  10.42200879  10.00212008  10.14618597  10.35100732]
 [ 10.49504246  10.39017443  10.70696161  10.2292809   10.76391887]
 [ 10.43283068  10.61598609  10.38632981  10.48332     10.57072346]]


[[-9.07557883 -9.23824946 -9.79814313 -9.7261335  -9.54429279]
 [-9.10280786 -9.86694766 -9.97994475 -9.57216325 -9.08491845]
 [-9.26085776 -9.57799121 -9.99787992 -9.85381403 -9.64899268]
 [-9.50495754 -9.60982557 -9.29303839 -9.7707191  -9.23608113]
 [-9.56716932 -9.38401391 -9.61367019 -9.51668    -9.42927654]]


[[ 9.24421172  7.6175054   2.01856873  2.73866495  4.55707208]
 [ 8.97192145  1.33052344  0.20055254  4.2783675   9.1508155 ]
 [ 7.39142238  4.22008791  0.02120083  1.46185965  3.51007318]
 [ 4.95042459  3.90174427  7.06961609  2.29280899  7.63918874]
 [ 4.32830676  6.15986085  3.86329812  4.83319997  5.70723457]]


[[ 0.09244212  0.0761

In [94]:
# Exponentiation

print(np.exp(arr))

[[ 2.52040896  2.14202264  1.22367286  1.31503923  1.57728846]
 [ 2.45270659  1.14230979  1.02025771  1.53393565  2.49697887]
 [ 2.09413847  1.52502193  1.00212233  1.15741141  1.42049772]
 [ 1.64056789  1.47723844  2.02782058  1.25769527  2.1466723 ]
 [ 1.54161517  1.85148142  1.47156993  1.62144868  1.76954678]]


In [95]:
# Natural logarithm

print(np.log(arr))

[[-0.0785875  -0.27213615 -1.60019638 -1.29511453 -0.78590476]
 [-0.10848523 -2.01701266 -3.90926411 -0.84901358 -0.08874209]
 [-0.3022649  -0.86272913 -6.15629987 -1.92287573 -1.04694821]
 [-0.70311174 -0.94116139 -0.34677892 -1.47280739 -0.26929368]
 [-0.83740868 -0.4845309  -0.95106384 -0.72707633 -0.5608505 ]]


In [96]:
# Base 2 logarithm

print(np.log2(arr))

[[-0.11337779 -0.39260948 -2.30859538 -1.86845532 -1.1338209 ]
 [-0.15651111 -2.90993417 -5.63987594 -1.22486768 -0.12802778]
 [-0.43607608 -1.24465504 -8.88166329 -2.77412328 -1.51042699]
 [-1.01437583 -1.35780887 -0.50029622 -2.12481192 -0.38850866]
 [-1.20812535 -0.69903033 -1.37209508 -1.04894941 -0.80913623]]


In [97]:
# Base 10 logarithm

print(np.log10(arr))

[[-0.03413012 -0.11818723 -0.69495646 -0.5624611  -0.3413141 ]
 [-0.04711454 -0.87597747 -1.69777183 -0.36872191 -0.0385402 ]
 [-0.13127198 -0.3746785  -2.67364706 -0.83509432 -0.45468383]
 [-0.30535755 -0.4087412  -0.15060417 -0.63963212 -0.11695276]
 [-0.36368197 -0.2104291  -0.41304178 -0.31576524 -0.24357428]]


In [98]:
# sin function

print(np.sin(arr))

[[ 0.79827227  0.69018924  0.20048885  0.27045585  0.44009746]
 [ 0.78157843  0.13266012  0.02005391  0.41490351  0.79261231]
 [ 0.67365423  0.40959383  0.00212008  0.14566585  0.34384388]
 [ 0.47506901  0.38034974  0.64952657  0.2272773   0.69175669]
 [ 0.41944212  0.57776365  0.37679127  0.46472145  0.54024099]]


In [102]:
print(np.sin(180))

-0.801152635734


In [100]:
print(np.sin(0))

0.0


In [103]:
# cos function

print(np.cos(arr))

[[ 0.60229676  0.72362892  0.97969598  0.96273238  0.89795001]
 [ 0.62380698  0.99116159  0.9997989   0.90986542  0.60972594]
 [ 0.73904667  0.91226799  0.99999775  0.98933385  0.93902683]
 [ 0.87994854  0.92484273  0.7603389   0.97383008  0.72213066]
 [ 0.90778208  0.81620412  0.92629819  0.88545693  0.84151035]]


In [104]:
print(arr)

[[ 0.92442117  0.76175054  0.20185687  0.2738665   0.45570721]
 [ 0.89719214  0.13305234  0.02005525  0.42783675  0.91508155]
 [ 0.73914224  0.42200879  0.00212008  0.14618597  0.35100732]
 [ 0.49504246  0.39017443  0.70696161  0.2292809   0.76391887]
 [ 0.43283068  0.61598609  0.38632981  0.48332     0.57072346]]


In [105]:
# sum along the row
print(np.sum(arr, axis=0))

[ 3.48862869  2.32297219  1.31732363  1.56049011  3.05643841]


In [107]:
# sum along the column
print(np.sum(arr, axis=1))

[ 2.61760229  2.39321804  1.6604644   2.58537827  2.48919003]


In [111]:
# minimum item value along the row
print(np.min(arr))

0.00212008336334


In [113]:
print(np.max(arr))

0.92442117211


In [115]:
# calculate the overall mean

print(np.mean(arr))

0.469834120936


In [116]:
# calculate the mean along the row

print(np.mean(arr, axis=0))

[ 0.69772574  0.46459444  0.26346473  0.31209802  0.61128768]


In [117]:
# calculate the median
print(np.median(arr))

0.432830675642


In [118]:
# calculate the standard deviation
print(np.std(arr))

0.265383503163


In [119]:
# calculate the variance
print(np.var(arr))

0.0704284037508


In [125]:
print(arr)
print('\n')
print(arr[1:3, 2:5])

[[ 0.92442117  0.76175054  0.20185687  0.2738665   0.45570721]
 [ 0.89719214  0.13305234  0.02005525  0.42783675  0.91508155]
 [ 0.73914224  0.42200879  0.00212008  0.14618597  0.35100732]
 [ 0.49504246  0.39017443  0.70696161  0.2292809   0.76391887]
 [ 0.43283068  0.61598609  0.38632981  0.48332     0.57072346]]


[[ 0.02005525  0.42783675  0.91508155]
 [ 0.00212008  0.14618597  0.35100732]]


In [137]:
# Sort an array
arr = np.random.rand(5,5)
print(arr)

[[ 0.66649804  0.05554176  0.80333758  0.28153103  0.66721317]
 [ 0.27678181  0.92490631  0.26128609  0.35851329  0.54536714]
 [ 0.82991016  0.93973673  0.57371009  0.39254232  0.48064887]
 [ 0.93697264  0.79075876  0.71471353  0.21048423  0.42465534]
 [ 0.93905423  0.72574336  0.11013662  0.34806501  0.43460982]]


In [140]:
# sort along the column

print(np.sort(arr, axis=1))

[[ 0.05554176  0.28153103  0.66649804  0.66721317  0.80333758]
 [ 0.26128609  0.27678181  0.35851329  0.54536714  0.92490631]
 [ 0.39254232  0.48064887  0.57371009  0.82991016  0.93973673]
 [ 0.21048423  0.42465534  0.71471353  0.79075876  0.93697264]
 [ 0.11013662  0.34806501  0.43460982  0.72574336  0.93905423]]


In [142]:
# Transpose an array
print(arr)
print('\n')
print(arr.T)

[[ 0.05554176  0.28153103  0.66649804  0.66721317  0.80333758]
 [ 0.26128609  0.27678181  0.35851329  0.54536714  0.92490631]
 [ 0.39254232  0.48064887  0.57371009  0.82991016  0.93973673]
 [ 0.21048423  0.42465534  0.71471353  0.79075876  0.93697264]
 [ 0.11013662  0.34806501  0.43460982  0.72574336  0.93905423]]


[[ 0.05554176  0.26128609  0.39254232  0.21048423  0.11013662]
 [ 0.28153103  0.27678181  0.48064887  0.42465534  0.34806501]
 [ 0.66649804  0.35851329  0.57371009  0.71471353  0.43460982]
 [ 0.66721317  0.54536714  0.82991016  0.79075876  0.72574336]
 [ 0.80333758  0.92490631  0.93973673  0.93697264  0.93905423]]


In [143]:
print(arr.transpose())

[[ 0.05554176  0.26128609  0.39254232  0.21048423  0.11013662]
 [ 0.28153103  0.27678181  0.48064887  0.42465534  0.34806501]
 [ 0.66649804  0.35851329  0.57371009  0.71471353  0.43460982]
 [ 0.66721317  0.54536714  0.82991016  0.79075876  0.72574336]
 [ 0.80333758  0.92490631  0.93973673  0.93697264  0.93905423]]


In [145]:
# Flatten the 2D array

print(arr)
print('\n')
print(arr.flatten())

[[ 0.05554176  0.28153103  0.66649804  0.66721317  0.80333758]
 [ 0.26128609  0.27678181  0.35851329  0.54536714  0.92490631]
 [ 0.39254232  0.48064887  0.57371009  0.82991016  0.93973673]
 [ 0.21048423  0.42465534  0.71471353  0.79075876  0.93697264]
 [ 0.11013662  0.34806501  0.43460982  0.72574336  0.93905423]]


[ 0.05554176  0.28153103  0.66649804  0.66721317  0.80333758  0.26128609
  0.27678181  0.35851329  0.54536714  0.92490631  0.39254232  0.48064887
  0.57371009  0.82991016  0.93973673  0.21048423  0.42465534  0.71471353
  0.79075876  0.93697264  0.11013662  0.34806501  0.43460982  0.72574336
  0.93905423]


In [146]:
# Append elements to an array

arr = np.array([4,5,6,7])

In [147]:
arr1 = np.append(arr, 8)
arr1

array([4, 5, 6, 7, 8])

In [149]:
arr2 = np.append(arr, [9,10,11])
print(arr2)

[ 4  5  6  7  9 10 11]


In [150]:
# Insert elements to an array

arr3 = np.insert(arr, 0, [12,13,14])
print(arr3)

[12 13 14  4  5  6  7]


In [154]:
# Remove elements from an array

print(arr)
print('\n')
arr4 = np.delete(arr, 0)
print(arr4)

[4 5 6 7]


[5 6 7]


In [162]:
# Delete multiple elements

print(arr2)
print('\n')
arr5 = np.delete(arr2, [1,4])
print(arr5)

[ 4  5  6  7  9 10 11]


[ 4  6  7 10 11]


In [166]:
# Copy elements from an array

arr1 = np.arange(10, 40, 3)
arr1

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [169]:
arr_copy = np.copy(arr1)
arr_copy

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37])

In [171]:
arr_copy = arr1.copy()
print(arr_copy)

[10 13 16 19 22 25 28 31 34 37]


In [172]:
# Combine and split an array

arr1 = np.array([[1,2,3,4], [1,2,3,4]])
arr2 = np.array([[5,6,7,8], [5,6,7,8]])

In [174]:
# Combine the array items by row

cat = np.concatenate((arr1,arr2), axis=0)
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [176]:
# Combine array items by column

cat = np. concatenate((arr1, arr2), axis=1)
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [177]:
# stack arrays vertically
cat = np.vstack((arr1, arr2))
print(cat)

[[1 2 3 4]
 [1 2 3 4]
 [5 6 7 8]
 [5 6 7 8]]


In [178]:
# Stack arrays horizontally
cat = np.hstack((arr1, arr2))
print(cat)

[[1 2 3 4 5 6 7 8]
 [1 2 3 4 5 6 7 8]]


In [179]:
# Set operations

# Find elements from an array
arr = np.array([1,2,3,4,5,6,3,6,1,2,4])
print(np.unique(arr))

[1 2 3 4 5 6]


In [180]:
# return the number of times each unique item appears
arr = np.array([1,1,2,2,3,3,4,5,6])
uniques, counts = np.unique(arr, return_counts=True)
print(uniques)
print(counts)

[1 2 3 4 5 6]
[2 2 2 1 1 1]


In [182]:
# Intersection of 2 array elements

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

In [183]:
print(np.intersect1d(arr1, arr2))

[3 4 5]


In [184]:
# Union of 2 array elements

print(np.union1d(arr1, arr2))

[1 2 3 4 5 6 7]


In [187]:
# Elements present in first array but not in the second array
print(np.setdiff1d(arr1, arr2))
print(np.setdiff1d(arr2, arr1))

[1 2]
[6 7]


In [188]:
# Elements present in either of the arrays but not both

print(np.setxor1d(arr1, arr2))

[1 2 6 7]
